pipeline {
    agent any
    stages {
        stage('Clone repository') {
          steps {
               checkout scm
               }
            }
        stage('Change directory') {
          steps {
               sh "pwd"
               dir('lesson7_Jenk') {
               sh "pwd"
               }
            } 
            }
          }
}
