pipeline {
    agent any
    stages {
        stage('Clone repository') {
          steps {
               checkout scm
               }
            }
        stage('Docker Build') {
          steps {
               sh 'docker build -t ubuntu:latest .'
      }
    }
          }
}
