pipeline {
    agent any
    stages {
        stage('Clone repository') {
          steps {
               checkout scm
               }
            }
        stage('Docker Build') {
          steps {
               sh 'docker build -t ubuntu:latest .'
      }
    }

stage('Docker tag') {
      steps {
           sh 'docker tag ubuntu:v1 hardynski/lesson5:v1'
        }
      }

stage('Docker Push') {
      steps {
        withCredentials([usernamePassword(credentialsId: '76be21d4-a90f-411e-80bb-a3cafb01e672', passwordVariable: 'vudhr42293', usernameVariable: 'hardynski')]) {
          sh 'docker push ubuntu:latest'
        }
      }
    }

          }
}
